apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: intersection-component
spec:
  environments:
    - name: prod
      build:
        from: master
  components:
    - name: storybook
      dockerfileName: storybook.Dockerfile
      ports:
        - name: nginx
          port: 80
      environmentConfig:
        - environment: prod
          variables:
            NODE_ENV: "production"
