name: Checks
on: [push]

jobs:
  setup:
    name: Checkout and install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: .npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Node version
        run: node --version
      - name: NPM version
        run: npm --version
      - name: Install dependencies
        run: |
          npm ci --cache .npm --prefer-offline
      - name: Cache base files
        uses: actions/cache@v2
        with:
          path: |
            ./*
            .npm
          key: ${{ github.sha }}
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Get files
        uses: actions/cache@v2
        with:
          path: |
            ./*
            .npm
          key: ${{ github.sha }}
      - name: Run linting
        run: npm run lint
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Get files
        uses: actions/cache@v2
        with:
          path: |
            ./*
            .npm
          key: ${{ github.sha }}
      - name: Run tests
        run: npm run test
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Get files
        uses: actions/cache@v2
        with:
          path: |
            ./*
            .npm
          key: ${{ github.sha }}
      - name: Build library
        run: npm run build
