name: Checks
on: [push]

jobs:
  setup:
    name: Checkout and install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          persist-credentials: false
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Node version
        run: node --version
      - name: NPM version
        run: npm --version
      - name: Install dependencies
        run: |
          npm ci --prefer-offline
      - name: Cache base files
        uses: actions/cache@v3
        with:
          path: |
            ./*
          key: ${{ github.sha }}
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Get files
        uses: actions/cache@v3
        with:
          path: |
            ./*
          key: ${{ github.sha }}
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Run linting
        run: npm run lint
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Get files
        uses: actions/cache@v3
        with:
          path: |
            ./*
          key: ${{ github.sha }}
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Run tests
        run: npm run test
  build:
    name: Build library
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Get files
        uses: actions/cache@v3
        with:
          path: |
            ./*
          key: ${{ github.sha }}
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Build library
        run: npm run build
  storybook:
    name: Build Storybook
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Get files
        uses: actions/cache@v3
        with:
          path: |
            ./*
          key: ${{ github.sha }}
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Build storybook
        run: |
          npm run build-storybook
        env:
          NODE_OPTIONS: --max-old-space-size=4096
