name: Checks
on: [push]

jobs:
  setup:
    name: Checkout and install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          persist-credentials: false
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Node version
        run: node --version
      - name: NPM version
        run: npm --version
      - name: Install dependencies
        run: |
          npm ci --prefer-offline
      - name: Cache base files
        uses: actions/cache@v3
        with:
          path: |
            ./*
          key: ${{ github.sha }}
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Get files
        uses: actions/cache@v3
        with:
          path: |
            ./*
          key: ${{ github.sha }}
      - name: Run linting
        run: npm run lint
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Get files
        uses: actions/cache@v3
        with:
          path: |
            ./*
          key: ${{ github.sha }}
      - name: Run tests
        run: npm run test
  build:
    name: Build library
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Get files
        uses: actions/cache@v3
        with:
          path: |
            ./*
          key: ${{ github.sha }}
      - name: Build library
        run: npm run build
  storybook:
    name: Build Storybook
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Increase Swap
        run: |
          echo "Memory and swap:"
          free -h
          echo
          swapon --show
          echo
          export SWAP_FILE=$(swapon --show=NAME | tail -n 1)
          sudo swapoff $SWAP_FILE
          sudo rm $SWAP_FILE
          sudo fallocate -l 2G $SWAP_FILE
          sudo chmod 600 $SWAP_FILE
          sudo mkswap $SWAP_FILE
          sudo swapon $SWAP_FILE
          echo "Memory and swap:"
          free -h
          echo
          swapon --show
          echo
      - name: Get files
        uses: actions/cache@v3
        with:
          path: |
            ./*
          key: ${{ github.sha }}
      - name: Build storybook
        run: npm run build-storybook
