name: Publish Beta Package

on:
  release:
    types: [prereleased]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org/'
      - run: npm ci
      - run: npm run pub-beta
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
